### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by huchinlp** [TharinduDR/TransQuest#1]
Hi,

This project is awesome and I am trying to reproduce some results you reported.

But I can't find documents about training the model.

If you are convenient, please disclose the training process and related configuration, 
which will greatly promote the development of the community.

Thank you so much!

**Comment by TharinduDR** [comment]
Thank you. 

I don't have the documents for training process at the moment. However, you will find many examples for the training process in the repository in the  [examples](../tree/master/examples/) folder. There you will see the training process for the language pairs in WMT QE shared tasks from 2018-2020. The configurations for the each language pair is inside its own directory.
