### ISSUE TITLE
Error: len() of unsized object

### ISSUE THREAD

**Issue by azat-khatyn** [TharinduDR/TransQuest#10]
Hello! 

I have attended the EMLP this year and learnt about TransQuest there. 
I am now  trying to train TransQuest with a very small dataset to check if it runs correctly.
However, I'm getting this error (`len() of unsized object`) and I'm not really sure, what might be causing it.
Among other things, it points to the `assert len(preds) == len(labels)`   failing.

By any chance, have you encountered this issue before? 

I'm using the `trans_quest.py` for the en-de pair in the WMT_2020_task2 folder as an example. 
The error occurs when executing code of lines 48 -97.

**Comment by TharinduDR** [comment]
Can you be more specific what are the steps you followed before this?
