### ISSUE TITLE
[Question] How would this do when evaluating cloud APIs?

### ISSUE THREAD

**Issue by kpister** [TharinduDR/TransQuest#11]
There are a bunch of cloud translation providers available these days, Google, AWS, IBM, and DeepL for example. 
I'd like to evaluate each provider's performance on something other than BLEU scores. If I'm understanding the project correctly, TransQuest should be the perfect tool for that, is that right?

Obviously, it will be imperfect and have inaccuracies, but so does BLEU. From the WMT results, it seems like this would be my best bet.

Mostly just wondering if I am crazy here. Happy to move this issue to an email chain if that is easier.

**Comment by TharinduDR** [comment]
Hi @kpister, 

Yeah, with TransQuest, you should be able to evaluate the outputs of machine translation engines and use the scores to select the best translation engine. 

From the two aspects, I think you should use the DA (Direct Assessment). Do you have any language pair in mind?

**Comment by kpister** [comment]
In particular I'm focused on Romance languages, but ideally I'd like to evaluate as many as possible to see which provider should be used for each language pair. 

I'm curious on your thoughts about potential dataset contamination. I'm not familiar with what TransQuest was trained on, but would it run into issues evaluating on GCloud/AWS if those services were trained on the same dataset? (i.e. it might falsely provide high scores since both translator and evaluator had same input pairing).

My assumption is google and amazon are using all the available data to train their models.

**Comment by TharinduDR** [comment]
I am sorry for the late reply, I have missed this. 

TransQuest was trained on quality estimation data in WMT 2020 shared task. Therefore, the dataset is source, target and the quality score which have not been used to train NMT models.. 

I hope I answered your question
