### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.modeling_albert'

### ISSUE THREAD

**Issue by leileilin** [TharinduDR/TransQuest#14]
Hello, After I had the above problem, I checked the folder under transformer, and I did not find the corresponding folder.
I wonder if that folder is a model for pretraining?

**Comment by TharinduDR** [comment]
Can you be more specific with what you are trying to do? Are you going to run the examples or use TransQuest as a library?

**Comment by leileilin** [comment]
Thank you man ! I have solved this issue. it just because the version of transformers is not  correct.
