### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by leileilin** [TharinduDR/TransQuest#15]
hey man . i have read the code in examples. But in transfomer_config.py, the exact meaning of some configurations is not very clear for me. can you upload a note for it?
Thank you man.

**Comment by TharinduDR** [comment]
Hi @leileilin, 

Yeah, I am working on that in the new release.

**Comment by leileilin** [comment]
> Hi @leileilin,
> 
> Yeah, I am working on that in the new release.

thank you man . 
expect !
