### ISSUE TITLE
some confusions

### ISSUE THREAD

**Issue by leileilin** [TharinduDR/TransQuest#16]
i have read the code in run_model.py, i find that num_labels variable, Is it possible to do word-level experiments by setting this variable？
I wonder if you offer word-level experiments?
thank you man .

**Comment by TharinduDR** [comment]
At the moment, it is not possible to do word-level experiments. 
Hopefully in the future! 😊

**Comment by TharinduDR** [comment]
We now support word-level quality estimation with the latest release - 1.0.0 😊

**Comment by leileilin** [comment]
> We now support word-level quality estimation with the latest release - 1.0.0 😊



> We now support word-level quality estimation with the latest release - 1.0.0 😊

thank you man. However, these two tasks are carried out separately, which is not multi task learning.
This is a pity.

**Comment by TharinduDR** [comment]
@leileilin yeah, we understand that, However, in order to support multi-task learning, the architecture needs to be changed in such a way that it has to implement multiple heads.

We are working on this in a future release

**Comment by leileilin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        thank you man.
        I'm looking forward to it.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1299192319
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/20/2021 19:49，Tharindu ***@***.***> wrote： 



@leileilin yeah, we understand that, However, in order to support multi-task learning, the architecture needs to be changed in such a way that it has to implement multiple heads.
We are working on this in a future release

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
