### ISSUE TITLE
[BUG]ImportError: cannot import name 'fit' from 'examples.sentence_level.wmt_2020_task2.common.util' (TransQuest/examples/sentence_level/wmt_2020_task2/common/util/__init__.py)

### ISSUE THREAD

**Issue by genbei** [TharinduDR/TransQuest#17]
when i run`python -m examples.sentence_level.wmt_2020_task2.en_zh.monotransquest`
this is wrong:
ImportError: cannot import name 'fit' from 'examples.sentence_level.wmt_2020_task2.common.util' (TransQuest/examples/sentence_level/wmt_2020_task2/common/util/__init__.py)

can you help me?thank you

**Comment by TharinduDR** [comment]
Can you be more specific on what are you trying to do because this command - python -m examples.sentence_level.wmt_2020_task2.en_zh.monotransquest works on my end without any issue. Did you change anything in the code?

**Comment by genbei** [comment]
> Can you be more specific on what are you trying to do because this command - python -m examples.sentence_level.wmt_2020_task2.en_zh.monotransquest works on my end without any issue. Did you change anything in the code?

no ，I just installed it just to run an example and found this problem.
Later, after I commented out this line, I encountered the following problems
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /xlm-roberta-large/01e55aa45dbb9164fee19aef60007a1c91d175051c01be1fb15056cfa60f3e53 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78d596cfd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

OSError: Can't load weights for 'xlm-roberta-large'. Make sure that:

- 'xlm-roberta-large' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'xlm-roberta-large' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.


`

**Comment by TharinduDR** [comment]
How did you install TransQuest?

**Comment by genbei** [comment]
git clone https://github.com/TharinduDR/TransQuest.git cd TransQuest pip install -r requirements.txt




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TharinduDR/TransQuest"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TharinduDR/TransQuest] [BUG]ImportError: cannot import name 'fit' from 'examples.sentence_level.wmt_2020_task2.common.util' (TransQuest/examples/sentence_level/wmt_2020_task2/common/util/__init__.py) (#17)





 
How did you install TransQuest?

**Comment by TharinduDR** [comment]
Oh that is fine then. 
The later error you are getting is because of your internet connection, Cn you try downloading xlm-roberta-large model manually and load it?

**Comment by genbei** [comment]
> Oh that is fine then.
> The later error you are getting is because of your internet connection, Cn you try downloading xlm-roberta-large model manually and load it?

Excuse me, where should I modify the code? Thank you very much

**Comment by TharinduDR** [comment]
line 55
` model = MonoTransQuestModel(MODEL_TYPE, MODEL_NAME, num_labels=1, use_cuda=torch.cuda.is_available(),
                                        args=monotransquest_config)`

instead of model_name give the path to manually downloaded model

**Comment by genbei** [comment]
> line 55
> ` model = MonoTransQuestModel(MODEL_TYPE, MODEL_NAME, num_labels=1, use_cuda=torch.cuda.is_available(), args=monotransquest_config)`
> 
> instead of model_name give the path to manually downloaded model
I rebuilt the environment and ran the example. It's still the same problem. I haven't modified the code. What's the problem


`(py) lyn19@amax:~/TransQuest$ python -m examples.sentence_level.wmt_2020_task2.en_zh.monotransquest
Traceback (most recent call last):
  File "/home/miniconda3/envs/py/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/miniconda3/envs/py/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/TransQuest/examples/sentence_level/wmt_2020_task2/en_zh/monotransquest.py", line 9, in <module>
    from examples.sentence_level.wmt_2020_task2.common.util.draw import draw_scatterplot, print_stat
  File "/home/TransQuest/examples/sentence_level/wmt_2020_task2/common/util/draw.py", line 4, in <module>
    from examples.sentence_level.wmt_2020_task2.common.util import fit
ImportError: cannot import name 'fit' from 'examples.sentence_level.wmt_2020_task2.common.util' (/home/TransQuest/examples/sentence_level/wmt_2020_task2/common/util/__init__.py)
`

**Comment by TharinduDR** [comment]
Thank you for the full stacktrace. There was a bug in the draw.py class. I have updated the code with this commit - https://github.com/TharinduDR/TransQuest/commit/c048d7107e0ba2db503cf54360059fcc3350241a. 
It should be fixed now. Please update the project and try again.
