### ISSUE TITLE
Getting  Error while finding module specification for 'examples.wmt_2020.en_de.trans_quest' (ModuleNotFoundError: No module named 'examples')

### ISSUE THREAD

**Issue by alokranjan04** [TharinduDR/TransQuest#2]
Error while finding module specification for 'examples.wmt_2020.en_de.trans_quest' (ModuleNotFoundError: No module named 'examples')

**Comment by TharinduDR** [comment]
Can you be more specific on what you are trying to do? What is the command you executed and what is the environment? Whether it was a pip install or a git clone?

**Comment by alokranjan04** [comment]
I need to calculate the Quality Score for the translation from Eng to German en-de. I downloaded the code and run requirements.txt then I downloaded pretrained model TransQuest-HTER-EN-DE .Then I run the command 

python -m examples.wmt_2020.en_de.trans_quest

But I could  not find this file wmt_2020.en_de.trans_quest.

Thanks for your help.

**Comment by TharinduDR** [comment]
First of all the documentation is not complete, I am attending to that - please bear it for a couple of weeks. There are two types of quality estimation goals experimented in this project. Predicting HTER and predicting Direct Assessment. You can read more about them here - http://www.statmt.org/wmt20/quality-estimation-task.html. Depending on your requirement you have to choose the pre-trained model and the python script.

If you want Direct Assessment the python script you want to look at is this - WMT 2020 QE Task 1 https://github.com/TharinduDR/TransQuest/blob/master/examples/wmt_2020/en_de/trans_quest.py. 

If you want HTER the python script you want to look at is this - WMT 2020 QE Task 2 https://github.com/TharinduDR/TransQuest/blob/master/examples/wmt_2020_task2/en_de/trans_quest.py. 

However, both of the scripts are for training a quality estimation model on WMT 2020 QE data. If you look at it carefully I have done predictions too in the script and you will be able to use them in the prediction.

**Comment by alokranjan04** [comment]
Thanks a lot for helping I am running this code .Is this available for English to Korean translation Quality Estimation or anyways I can train it for the same.

Thanks again,
Alok

**Comment by TharinduDR** [comment]
I don't have a pre-trained model for English-Korean, However, if you have quality estimation data for English-Korean, you can use the framework. The base model that I used for TransQuest - xlm-roberta-large supports Korean. Therefore the method should work for English-Korean too

**Comment by alokranjan04** [comment]
Hi Thaindu . Thanks for your help .I ran the en_de model and I have few query
1. What is the labels and predictions score. Is it percentage or TF_DF score or something else
2. It took me 24 hrs to run the code so if I run it again, from where I can point to the trained model so that it should not go take so much time again

**Comment by TharinduDR** [comment]
1. labels and the predictions score depends on the objective. As I mentioned above it is either HTER (http://statmt.org/wmt17/pdf/WMT58.pdf) or Direct Assessment (https://iconictranslation.com/2020/06/issue-84-are-neural-machine-translation-systems-good-estimators-of-quality/). If you are not familiar with translation quality estimation, I strongly recommend you to read them. 

2. It should be faster with a good GPU. I worked with Nvidia Tesla K80 GPU and it didn't take more than 9 hours. However, you can provide the path to the last checkpoint in temp/outputs directory as "MODEL_NAME" in configurations and it will resume the training from that point. However, if you just want to use the trained model for inference just run following two lines, it will give the predictions, 

`model = QuestModel(MODEL_TYPE, transformer_config["best_model_dir"], num_labels=1,
                           use_cuda=torch.cuda.is_available(), args=transformer_config)

predictions, raw_outputs = model.predict(test_sentence_pairs)`

3. It doesn't do the translations. The purpose of the project is to provide quality estimation for a given translation

**Comment by alokranjan04** [comment]
Hi TharinduDR business requirement is to build a model which can provide me  the percentage confidence score so that i can put a threshold for.Let us say 75% is the threshold  If the quality of the translation is less than 75% ,there will be different business rule applied.If the same threshold confidence score is above 75% .We will consider the quality and the quality should be calculated within fraction of sec (less than 100ms) .I can see that model.predict is taking more than a minute to compute the same.

**Comment by TharinduDR** [comment]
Are you using a GPU?

It will be efficient to predict in batches. For an example in my setup, using a Tesla K80 GPU it only takes 35s to predict on 1000 sentences which is approximately 35ms for an instance.

**Comment by alokranjan04** [comment]
Hi TharinduDR 

How will I get the percentage of accuracy. As prediction I am getting in numbers which is like 0.15 , 0.16

**Comment by TharinduDR** [comment]
What is the example you are working on?

**Comment by alokranjan04** [comment]
Hi TharinduDR business requirement is to build a model which can provide me the percentage confidence score so that i can put a threshold for making business decision.Good score means good quality of the translation, bad score means bad quality of translation.The score should lie between 0 -1

**Comment by TharinduDR** [comment]
What is the dataset you are working on? Do you have a different dataset?

**Comment by alokranjan04** [comment]
No it's a chatbot it can be anything sentence in english to german translation confidence score and therefore there should not be any delay otherwise chat will be slow.

**Comment by TharinduDR** [comment]
If you are using this function to predict, it gives a score between 0-1. 

`predictions, raw_outputs = model.predict(test_sentence_pairs)`

**Comment by alokranjan04** [comment]
If I am using 

 model.predict([['I am Alok','I Alok']])                                       prediction = 0.17117941       
model.predict([['I am Alok','testing if it is correct']])              prediction = 0.18209016
model.predict([['I am Alok','Ich bin Alok']])                              prediction = 0.17428833  This is the correct translation it should be atleast above 0.9 


Now how can I identify the correctness from this prediction and what threshold should I put

**Comment by TharinduDR** [comment]
The model is trained on data from Wikipedia. See the training file here - https://raw.githubusercontent.com/TharinduDR/TransQuest/master/examples/wmt_2020/en_de/data/en-de/train.ende.df.short.tsv

It is not going to work if you are using it for a different domain and using it to evaluate a different neural machine translation system. I suggest you to train the model on your dataset and evaluate it.

**Comment by dmar1n** [comment]
Hi Alok, you can also create your own test set (using human translations --preferably post-edits-- and HTER, which measures the distance between the machine translations and their human versions), then predict the quality on the same sources of the test set, and see the correlation between the predicted scores and the real scores. If the predictions correlate somehow with the real scores, it probably means you can use the estimation model. If the correlation is weak (<20), what TharinduDR suggests is the proper course of action. Then, the threshold to decide what is good or bad is just up to you, it should just reflect what you consider fit for purpose in your particular use case.

**Comment by alokranjan04** [comment]
Can we have a meeting today so that you can help me with my dataset ?

**Comment by alokranjan04** [comment]
Hi TharinduDR I had a demo yesterday with my manager about transquest if we can use this.for my confidence score. I found that even if I am using the exact the same training datasets ,I am getting the prediction between 0.15 and 0.16. What does this signifies as the sentence which is 100% correct should be 0.98 or 0.99

**Comment by TharinduDR** [comment]
Do you have a proper test set as @dmar1n mentioned and if you do what is the Pearson Correlation you get for that?

**Comment by alokranjan04** [comment]
The model is trained on _wmt_2020/en_de/data/en-de/train.ende.df.short.tsv_ .And I am just validating the already trained datasets 

model_outputs = [["However, a   disappointing ninth in China meant that he dropped back to sixth in the   standings.","Eine enttÃ¤uschende   Neunte in China bedeutete jedoch, dass er in der Gesamtwertung auf den   sechsten Platz zurÃ¼ckfiel."']]

model.predict(test_sentence_pairs)

**Comment by TharinduDR** [comment]
There is no point of just testing it sentence by sentence. You need at least 1000 sentences for testing. That is why when you are running this code - https://github.com/TharinduDR/TransQuest/blob/master/examples/wmt_2020_task2/en_de/trans_quest.py it does an automatic evaluation on an unseen evaluation set and prints the results at last. What are the values it prints when you run the code?

**Comment by TharinduDR** [comment]
I understand the business requirement. What I am saying is in order to evaluate a machine learning model properly, you need to have a test set of that size. Then only we can monitor whether a certain machine learning model solves a problem or not. You can't expect a machine learning model to predict each and every sentence correctly since no machine learning model is 100% perfect. 

Looking at your image I suspect that the model has not been trained correctly. That is why I asked what are the Pearson correlation values it prints at the end of the training?

**Comment by alokranjan04** [comment]
[English sentence for Quality ES.xlsx](https://github.com/TharinduDR/TransQuest/files/5123515/English.sentence.for.Quality.ES.xlsx)
Hi TharinduDR can you please guide me for these sentences, how can I create the datasets for the same for english to korean and get the translation quality score for the same.

**Comment by TharinduDR** [comment]
First, translate those sentences to Korean using the same machine translation system you are using for the chat application. Then find a few annotators who are proficient in both Korean and English. Ask them to rate the translation. From that file you can prepare a training file and a validation file. 

Then you can use TransQuest to build a quality estimation model.
