### ISSUE TITLE
Is it possible to train in two stages? Under two different corpora

### ISSUE THREAD

**Issue by genbei** [TharinduDR/TransQuest#21]
Thank you very much, such as topic

**Comment by TharinduDR** [comment]
Yeah it is possible. Train a TransQuest model on one corpora and save the weights. Load that weights from a local path when you start the training for next corpora

**Comment by genbei** [comment]
> Yeah it is possible. Train a TransQuest model on one corpora and save the weights. Load that weights from a local path when you start the training for next corpora
 
thank you，I will try

I have another question. The eval_results.txt in outputs is different from the eval_results.txt in best_model. Which is the score of the verification set? The training_progress_scores.csv stores the training results of each step. The highest score here should be the score.

**Comment by TharinduDR** [comment]
> And what should I do if I train the model and only want to make predictions?
The question is not clear. The model makes the predictions once it is trained properly. 


> have another question. The eval_results.txt in outputs is different from the eval_results.txt in best_model. What do they stand for？
The eval_results.txt in outputs is the results for the last model while eval_results.txt in best_model is the results for best model.

**Comment by genbei** [comment]
> > 如果我训练模型并且只想做出预测，该怎么办？
> > 问题尚不清楚。模型经过正确训练后即可做出预测。
> 
> > 还有一个问题。输出中的eval_results.txt与best_model中的eval_results.txt不同。它们代表什么？
> > 输出中的eval_results.txt是最后一个模型的结果，而best_model中的eval_results.txt是最好的模型的结果。
