### ISSUE TITLE
[BUG] CANNOT access TransQuest website

### ISSUE THREAD

**Issue by conanjgz** [TharinduDR/TransQuest#24]
I tried to visit the TransQuest website (many links you provided in README.md) but was told that 

> tharindu.co.uk
> is parked free, courtesy of GoDaddy.com.

Here is the screen shot of the problem:
![image](https://user-images.githubusercontent.com/30578619/120062169-a4d4da00-c058-11eb-9432-dc5c8816f12f.png)

Could you fix that?

**Comment by TharinduDR** [comment]
That is quite strange, because I checked it with several computers here and all the links work - 
![image](https://user-images.githubusercontent.com/1343224/120067269-824fba80-c072-11eb-82dd-e2e79e48216a.png)

From where are you trying to access TransQuest site? is it possible to do that with an incognito browser?

**Comment by conanjgz** [comment]
Sorry for the late response.
I am in London and I cannot access it even with an incognito browser. The same problem appeared on my friend's computer as well. I also tried to use a vpn but it still didn't work.

**Comment by TharinduDR** [comment]
Are you behind a vpn?

**Comment by conanjgz** [comment]
No, I directly connect to the internet provided by my apartment. I tried many times from different devices and found that sometimes the website is accessable but if I refresh the page later, the problems appears again. It is quite weird.

**Comment by TharinduDR** [comment]
I have changed some settings. Will you be able to check again?

**Comment by conanjgz** [comment]
Just checked the website and it temporarily works on my iPad. Once I refresh the page the same problems appear again.

**Comment by TharinduDR** [comment]
Does the issue still remain?

**Comment by conanjgz** [comment]
I just checked it and the issue has been solved! I can now access it from all my devices. 
Thank you.
