### ISSUE TITLE
Pretrained model for En-Ru direct assessment?

### ISSUE THREAD

**Issue by dsorato** [TharinduDR/TransQuest#28]
Hi,
A question about a pretrained model: [in this page](https://tharindu.co.uk/TransQuest/models/sentence_level_pretrained/) you say that the monotransquest-da-multilingual model works for any language pair but is not clear which are the languages. So, just to make sure, does this pretrained model have support for  En-Ru direct assessment?

Thanks in advance.

**Comment by TharinduDR** [comment]
It was trained on En-De, En-Zh, Ru-En, Ne-En, Si-En, Et-En, Ro-En language pairs. But we have shown in the paper that it should work pretty well for an unseen language pair too, that is why we have mentioned as the monotransquest-da-multilingual model works for any language pair.

**Comment by dsorato** [comment]
I see, many thanks for the clarification!
