### ISSUE TITLE
Were the scores normalized before using as labels?

### ISSUE THREAD

**Issue by DebanjanaKar** [TharinduDR/TransQuest#30]
Hi @TharinduDR , I am using the Siamese Network model. Since it uses a cosine similarity loss, are the DA scores normalized to be within the range 0-1 when you are using it in the model?

**Comment by TharinduDR** [comment]
No, you have to normalise them before feeding them to the model. You can see the example here - https://github.com/TharinduDR/TransQuest/blob/master/examples/sentence_level/wmt_2020/en_de/siamesetransquest.py

lines 45,46

**Comment by DebanjanaKar** [comment]
Thanks a lot, I am trying to reproduce the results for en-de with the script you mentioned above. 
1. Should it produce the results (0.3992 | 0.6651 | 0.8497) mentioned here: https://tharindu.co.uk/TransQuest/examples/sentence_level_examples/? I have not changed the config file from this repo.
2. How much time does it take to run on your GPU server?

**Comment by TharinduDR** [comment]
You are welcome :slightly_smiling_face:

1. Yeah, you should. 
2. I don't remember the exact time. But it took around 1.5 hours as I remember.

**Comment by DebanjanaKar** [comment]
Hey, thanks. I'll keep you posted regarding what scores I get. However, I am running the same on a v100 server, it is taking 4 hours per epoch. :(
