### ISSUE TITLE
en-de monotransquest DA example cannot reproduce the result

### ISSUE THREAD

**Issue by shachardon** [TharinduDR/TransQuest#32]
Hi, thank you for sharing the code!

1. I’m trying to reproduce the results on en-de test20 DA.  When I train the model with _examples/sentence_level/wmt_2020/en_de/monotransquest.py_, I get pearson correlation of 0.41, while in the paper you reported 0.46. More than that, I’m pretty sure that a couple of months ago I trained it and got something similar to 0.46 too.
I speculate this is related to the numpy/torch versions (I don't have the old virtual env I used then). What are the exact versions you used? Do you have any idea what might cause this drop?

2. In the paper you created augmentations from the parallel training data to boost the performances. I experimented with the augmentations myself, and didn’t manage to make it improve the results. Did you use some heuristics to choose the pairs you used, other than just sampling them randomly?

**Comment by ardate** [comment]
I also encountered this issue. I am providing the torch and numpy versions I used, in case this helps: torch==1.10.2, numpy==1.22.3. I would also be happy to hear how the results from the paper can be reproduced. Thanks!
