### ISSUE TITLE
Problem with the monotransquest-hter-en_cs model

### ISSUE THREAD

**Issue by kukas** [TharinduDR/TransQuest#38]
Hi! I wanted to use the `TransQuest/monotransquest-hter-en_cs-pharmaceutical` model but it outputs the same constant for any input sentences. Other models work well so it seems that this model in particular is broken.

May I kindly ask you to upload fixed model? Thank you

For the bug replication check out this Colab: https://colab.research.google.com/drive/1ujKgV8aS7E9XjNz02pdh7vhYDpDAuH_m#scrollTo=npg2206l9Z7b

**Comment by ben-xl8** [comment]
Hi!, was just wondering if you ever came up with a fix to this issue?

**Comment by kukas** [comment]
Hey, sadly not. If I remember correctly I used COMET reference free models instead. Hope that helps!

**Comment by ben-xl8** [comment]
That does help, thank you!
