### ISSUE TITLE
Can you provide the latest configuration of the wmt_2020_task2 ?

### ISSUE THREAD

**Issue by chencong-jxnu** [TharinduDR/TransQuest#4]
I run the `trans_quests.py` script in `examples/wmt_2020_task2/en_zh/`.   
Finally, I got the `predictions.txt` file in `temp/data/`. I submitted it to CodaLab, the Pearson correlation is `0.5999`. 
CodaLab showed that TransQuest's best result in `en-zh` is `0.6119`. 
So, can you provide the latest configuration of the wmt_2020_task2 ?

Thanks for your help.

**Comment by TharinduDR** [comment]
Configurations are the same. We just concatenated dev file with the training file before the training procedure got started.

**Comment by chencong-jxnu** [comment]
I get it, thank you very mach.
