### ISSUE TITLE
ne-en pretrained model cannot reproduce results

### ISSUE THREAD

**Issue by myusufkocyigit** [TharinduDR/TransQuest#8]
The Ne-En pretrained model in the model zoo is either mixed with another language pair or is uploaded without training. When I run the eval script with the gdrive file I get a correlation around 0.2

**Comment by TharinduDR** [comment]
I will check it again. Is there any chance that you can run this file - https://github.com/TharinduDR/TransQuest/blob/master/examples/wmt_2020/ne_en/trans_quest.py so that you can train Ne-En model from scratch and let me know the results?

**Comment by myusufkocyigit** [comment]
Hi I haven't tried this but trained a new XLM-R model and the results are much close to that of the paper. So I think it is probably a simple mixup

**Comment by TharinduDR** [comment]
With the new release we have fixed this. You can find the new models here - https://tharindudr.github.io/TransQuest/models/sentence_level_pretrained/
